spring.application.name=SchoolManagement
debug=true

server.port=8080

# JWT Configuration
app.jwt.secret=MySuperSecretKeyForSchoolManagementSystem123!

# CORS Allowed Origins (Comma separated)
app.cors.allowed-origins=http://localhost:4200,https://school-management-ui-psi.vercel.app

# to store the images 
# Cloudinary Configuration
cloudinary.url=cloudinary://641569417564525:sd9QVpLE8z9EMV3btMAryLXEEsE@dwbtdkomf

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
#spring.datasource.url=jdbc:postgresql://localhost:5431/mydatabase?options=-c%20timezone=Asia/Kolkata
#spring.datasource.username=myuser
#spring.datasource.password=mypassword


spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=Postgres@123

#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG